# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-power-manager
    - file
    - gcc
    - git
    - intltool
    - itstool
    - libgnome-keyring
    - libnotify
    - make
    - mate-common
    - mate-panel
    - python
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-power-manager
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libgcrypt20-dev
    - libglib2.0-dev
    - libgnome-keyring-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libnotify-dev
    - libtool-bin
    - libupower-glib-dev
    - libx11-dev
    - libxext-dev
    - libxml-parser-perl
    - libxrandr-dev
    - make
    - mate-common
    - pkg-config
    - xmlto
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-power-manager.git
    - cairo-devel
    - dbus-glib-devel
    - desktop-file-utils
    - gcc
    - git
    - glib2-devel
    - gtk3-devel
    - libcanberra-devel
    - libgnome-keyring-devel
    - libnotify-devel
    - make
    - mate-common
    - mate-panel-devel
    - mesa-libGL-devel
    - pangox-compat-devel
    - popt-devel
    - redhat-rpm-config
    - upower-devel

  ubuntu:
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libgcrypt20-dev
    - libglib2.0-dev
    - libgnome-keyring-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libnotify-dev
    - libtool-bin
    - libupower-glib-dev
    - libx11-dev
    - libxext-dev
    - libxml-parser-perl
    - libxrandr-dev
    - make
    - mate-common
    - pkg-config
    - xmlto
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck
